from je_auto_control.utils.je_auto_control_exception.exceptions import ImageNotFoundException

raise ImageNotFoundException("test.png")
